### PR TITLE
Add proper logic for yellow letters

### LINKED ISSUE #2: Letter highlights in yellow if it's already highlighted elsewhere in green and only once in the word
Kilordle

In the original game if a letter appears more than once in a trial word, but only once in the final result, the letter only gets highlighted once, priority being the leftmost, unless the other one is in the correct position, in which, that would be the only highlighted letter. Never would the above screenshot take place.

### PR DESCRIPTION
**Pull request by kav2k**
Follows proper Wordle logic for misplaced guesses, fixes #2

### CODE REVIEW

**Comment by kav2k** [comment]
Oops, I need to double-check this.
~~Edit: yes, nevermind, the logic is completely wrong, need to rewrite.~~

**Comment by kav2k** [comment]
Okay, I'm just paranoid. It seems to work fine after some testing.

The rules are as follows:
- Highlight exact guesses as green.
- Go over non-highlighted letters, left to right. Highlight yellow if:
  - Is in the target word
  - The total number of highlighted instances of this letter is not greater than total number in the target word

Algorithm is as follows:

- If the guess letter is an exact match, it's not yellow (it's green)
- Otherwise, count the number N of occurrences of that letter that aren't exactly matched in the target word.
- Then, count the number M of occurrences of that letter that aren't exactly matched in the part of guess before current index.
- If M < N, then it's yellow, otherwise do not highlight (because the total would be more than in the target).

**Comment by kav2k** [comment]
Examples of it working (with a "cheat" of the intended word being visible)
image

**Review by jonesnxt — APPROVED** [review]
I was worried about performance for yellow finding, but this looks good, Thank you!

**Pull request merged**
