### PR TITLE
End screen

### PR DESCRIPTION
**Pull request by toBeOfUse**
I thought it would be nice if this game had an end screen, so I added one that generates a nice progress graph with HTML canvas:

image

The share button tries to copy the image to the clipboard and if it is prevented it tries to save the image. 

I'm going to be honest, I haven't tested it out by playing a game start to finish, but there's a commented-out section of code in App.tsx that simulates the game being won and shows the `EndScreen` component visually responding correctly to the props being passed in. Also, I added a constant `totalWords` in that component that can be changed to test it with shorter games.

### CODE REVIEW

**Comment by jonesnxt** [comment]
Very cool, I'll do a review of it tomorrow and make a couple tweaks. Thanks for putting this together!

**Review by jonesnxt — APPROVED** [review]
oops let this sit for longer than I wanted but now I have a sec and it'll be live in like 30ish minutes.

**Comment by patarapolw** [comment]
It would be nice if the share-able gets a mobile support (Vivo Android, to be exact), other than saving an Image file. Otherwise, the Image should be named according to finish time (in that time zone), like `kilordle-2022-04-03-2141.png`.

**Comment by toBeOfUse** [comment]
I might open a PR later to try out the navigator.share API, which I've never used or heard of but which seems to be supported on most mobile devices, change the filename like you suggested, and move the URL down a bit in the image

**Pull request merged**
